#    snapcraft yaml for tux-paint.
#    Copyright (C) 2021-2022 joker2770
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: tux-paint
version: '0.9.29' # just for humans, typically '1.2+git' or '1.3.2'
summary: An award-winning drawing program for children of all ages. # 79 char long summary
description: |
  Tux Paint is a free, award-winning drawing program originally created for children ages 3 to 12,
  but enjoyed by all! It combines an easy-to-use interface, fun sound effects, and an encouraging
  cartoon mascot who guides children as they use the program.

  You're presented with a blank canvas and a variety of drawing tools to help them be creative.
  Along with paintbrush, shapes and text, Tux Paint includes a "stamp" feature to add pre-drawn
  or photographic imagery to pictures, and a set of "magic tools" that provide filter effects
  (like blur, tint and waves) and interesting drawing tools (like train tracks, bubbles and grass).

  Tux Paint includes a collection of "starter" images, both coloring-book style and photo-realistic,
  and a large collections of stamps are available as a separate download. Additional content
  can be added by parents & teachers, or downloaded from 3rd parties.

  Tux Paint is available for Windows, macOS, Android, Linux, & Haiku operating systems, among others.

  _More build details: https://github.com/Joker2770/TuxPaint-snap _

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  
apps:
  tux-paint:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/local/bin/tuxpaint
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    extensions: [gnome-3-38]
    plugs:
      - home
      - audio-playback
      - pulseaudio
      - alsa
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - gsettings
      - removable-media
        
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/local/share/locale:
    bind: $SNAP/usr/local/share/locale
  /usr/local/share/tuxpaint:
    bind: $SNAP/usr/local/share/tuxpaint
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/fonts:
    bind: $SNAP/etc/fonts
    
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  tux-paint:
    after: [alsa-mixin]
    plugin: make
    source: "https://git.code.sf.net/p/tuxpaint/tuxpaint"
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
      - gcc
      - make
      - gperf
      - gettext
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libsdl-pango-dev
      - libsdl-ttf2.0-dev
      - libsdl-mixer1.2-dev
      - libsdl-gfx1.2-dev
      - librsvg2-dev
      - libfribidi-dev
      - libpaper-dev
      - libimagequant-dev
    stage-packages:
      - libsdl1.2debian
      - libsdl-image1.2
      - libsdl-pango1
      - libsdl-ttf2.0-0
      - libsdl-mixer1.2
      - libsdl-gfx1.2-5
      - libpulse0
      - librsvg2-2
      - librsvg2-common
      - libfribidi0
      - libpaper1
      - libimagequant0
      - freeglut3
      - libglu1-mesa
    override-build: |
      make -j $(nproc) tuxpaint
      make -j $(nproc) magic-plugins
      make -j $(nproc) tp-magic-config
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin
      cp ./tuxpaint ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      sudo make install-bin DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-data DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-magic-plugins DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-magic-plugin-dev DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-default-config DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-example-stamps DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-example-starters DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-example-templates DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-icon DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-osk DESTDIR=/build/tux-paint/parts/tux-paint/install
      sudo make install-im DESTDIR=/build/tux-paint/parts/tux-paint/install
